ADD - Error message to stderr for backup scripts

diff --git a/daily_snapshot b/daily_snapshot
--- a/daily_snapshot
+++ b/daily_snapshot
@@ -24,18 +24,24 @@ MOUNT_RO=/home/miguel/hdd2;
 SNAPSHOT_RW=/root/snapshot;
 
 
+# ------------- Helper functions ------------------------------------------------------------------
+error() {
+    $ECHO $1 >&2
+}
+
+
 # ------------- The script itself -----------------------------------------------------------------
 
 # make sure we're running as root
-if (( `$ID -u` != 0 )); then { $ECHO "Sorry, must be root.  Exiting..."; exit; } fi
+if (( `$ID -u` != 0 )); then { error "Sorry, must be root.  Exiting..."; exit 1; } fi
 
 # attempt to remount the RW mount point as RW; else abort
 $MOUNT --bind $MOUNT_RO $SNAPSHOT_RW ;
 $MOUNT -o remount,rw $MOUNT_RO $SNAPSHOT_RW ;
 if (( $? )); then
 {
-    $ECHO "snapshot: could not remount $SNAPSHOT_RW readwrite";
-    exit;
+    error "snapshot: could not remount $SNAPSHOT_RW readwrite";
+    exit 1;
 }
 fi;
 
@@ -92,6 +98,6 @@ fi;
 $UMOUNT $SNAPSHOT_RW ;
 if (( $? )); then
 {
-    $ECHO "snapshot: could not umount $SNAPSHOT_RW";
-    exit;
+    error "snapshot: could not umount $SNAPSHOT_RW";
+    exit 1;
 } fi
diff --git a/make_snapshot b/make_snapshot
--- a/make_snapshot
+++ b/make_snapshot
@@ -28,18 +28,24 @@ SNAPSHOT_RW=/root/snapshot;
 EXCLUDES=
 
 
+# ------------- Helper functions ------------------------------------------------------------------
+error() {
+    $ECHO $1 >&2
+}
+
+
 # ------------- The script itself -----------------------------------------------------------------
 
 # Make sure we're running as root
-if (( `$ID -u` != 0 )); then { $ECHO "Sorry, must be root.  Exiting..."; exit; } fi
+if (( `$ID -u` != 0 )); then { error "Sorry, must be root.  Exiting..."; exit 1; } fi
 
 # Attempt to remount the RW mount point as RW; else abort
 $MOUNT --bind $MOUNT_RO $SNAPSHOT_RW ;
 $MOUNT -o remount,rw $MOUNT_RO $SNAPSHOT_RW ;
 if (( $? )); then
 {
-    $ECHO "snapshot: could not remount $SNAPSHOT_RW readwrite";
-    exit;
+    error "snapshot: could not remount $SNAPSHOT_RW readwrite";
+    exit 1;
 }
 fi;
 
@@ -95,6 +101,6 @@ $TOUCH $SNAPSHOT_RW/hourly.0 ;
 $UMOUNT $SNAPSHOT_RW ;
 if (( $? )); then
 {
-    $ECHO "snapshot: could not umount $SNAPSHOT_RW";
-    exit;
+    error "snapshot: could not umount $SNAPSHOT_RW";
+    exit 1;
 } fi
